import java.io.IOException;
import java.nio.file.Path;
import java.nio.file.Paths;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) throws IOException {
        //String path = args[0];
        Path filePath = Paths.get("D:/java_Course/bitmap-transformer/src/main/resourses", "baldy-8bit.bmp");
        Bitmap bitmap = new Bitmap();
        bitmap.readFile(filePath);
    }
}
